name: Setup Node.js
description: Prepare and install everything for Node.js

inputs:
  node-version:
    description: Version of Node to use
    default: 22.x

  npm-registry-url:
    description: npm registry url
    default: ""

runs:
  using: composite
  steps:
    - name: 🏗 Setup pnpm
      uses: pnpm/action-setup@v4

    - name: 🏗 Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
        registry-url: ${{ inputs.npm-registry-url }}

    - name: 📦 Install dependencies
      run: pnpm install
      shell: bash

    - name: 📦 Install dependencies (example)
      run: pnpm install
      shell: bash
      working-directory: example
